In [1]:
''' 
Numpy :

*Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, 
and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.

*In Python we have lists that serve the purpose of arrays, but they are slow to process.

*NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

*The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working 
with ndarray very easy.

*Arrays are very frequently used in data science, where speed and resources are very important.
'''

' \nNumpy :\n\n*Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, \nand tools for working with these arrays. It is the fundamental package for scientific computing with Python.\nBesides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.\n\n*In Python we have lists that serve the purpose of arrays, but they are slow to process.\n\n*NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.\n\n*The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working \nwith ndarray very easy.\n\n*Arrays are very frequently used in data science, where speed and resources are very important.\n'

In [5]:
import numpy as np

In [3]:
# one dimensional array 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#2D array
b = np.array([[1.0,3.0,3.0],[9.0,6.0,4.0]])
print(b)

[[1. 3. 3.]
 [9. 6. 4.]]


In [5]:
# get dimension 
a = np.array([1,2,3])
print(a)
a.ndim

[1 2 3]


1

In [6]:
b.ndim

2

In [7]:
# get shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# get type 
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [11]:
a = np.array([1,2,3] , dtype = 'int16')
print(a)

a.dtype

[1 2 3]


dtype('int16')

In [12]:
# get size

a = np.array([1,2,3])

print(a.dtype)

print(a.itemsize)

int32
4


In [13]:
a = np.array([1,2,3] , dtype = 'int16')

print(a.dtype)
print(a.itemsize)

int16
2


In [14]:
# get total size
a = np.array([1,2,3])
a.size

3

In [15]:
a.size * a.itemsize

12

In [16]:
# same as above 
a.nbytes

12

In [17]:
# ACCESSING/CHANGING SPECIFIC ELEMENTS , ROWS , COLUMNS ETC

c = np.array([[1,5,3,9,2,4,8] , [4,1,8,3,2,9,5]])
print(c)

[[1 5 3 9 2 4 8]
 [4 1 8 3 2 9 5]]


In [18]:
c.shape

(2, 7)

In [19]:
# get specific element [row,column]
print(c[0,5])
print(c[1,5])
print(c[0,-1])

4
9
8


In [20]:
# get specific row
c[0,:]

array([1, 5, 3, 9, 2, 4, 8])

In [21]:
# get specific column
c[:,2]

array([3, 8])

In [22]:
# getting little more fancy [ startindex : endindex : stepsize ]
c = np.array([[1,5,3,9,2,4,8] , [4,1,8,3,2,9,5]])
c[0, 1:5:1]

array([5, 3, 9, 2])

In [23]:
c[1, 1:-2:1]

array([1, 8, 3, 2])

In [24]:
c[1, 1:-1:1]

array([1, 8, 3, 2, 9])

In [25]:
c = np.array([[1,5,3,9,2,4,8] , [4,1,8,3,2,9,5]])
c[0,3] = 11
c[1,6] = 0
print(c)

[[ 1  5  3 11  2  4  8]
 [ 4  1  8  3  2  9  0]]


In [26]:
c[1,:] = 1
print(c)

[[ 1  5  3 11  2  4  8]
 [ 1  1  1  1  1  1  1]]


In [27]:
c[:,3] = 0
print(c)

[[1 5 3 0 2 4 8]
 [1 1 1 0 1 1 1]]


In [28]:
d = np.array([1,2,3])
e = np.array([6,3,8])
d*e

array([ 6,  6, 24])

In [29]:
x = np.array([[7,2,6] , [2,4,8] , [1,8,4]])
y = np.array([[9,4,7] , [1,3,9] , [6,3,8]])
x*y

array([[63,  8, 42],
       [ 2, 12, 72],
       [ 6, 24, 32]])

In [30]:
f = np.array([[[1,2] , [3,4]] , [[5,6] , [7,8]]])
print(f)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
print(f[:,0,:])
print(f[0,1,1])
print(f[:,1,:])



[[1 2]
 [5 6]]
4
[[3 4]
 [7 8]]


In [32]:
print(f[:,0,0])
print(f[:,1,1])

[1 5]
[4 8]


In [33]:
#replace
f[:,1,:] = [[9,9] , [8,8]]
print(f)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [34]:
f[:,1,:] = [[9,9,9] , [8,8]]
print(f)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [35]:
# Initializing different types of arrays

# all 0's matrix

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [39]:
# all 1's matrix
np.ones(3)

array([1., 1., 1.])

In [40]:
np.ones((2,5), dtype = 'int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
# any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [42]:
np.full((2,2),99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [43]:
# any other number (full_like)

s = np.array([[1,2,3,4,5] , [6,7,8,9,10]])
print(s)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [44]:
np.full_like(a.shape,4)

array([4])

In [45]:
print(s)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [46]:
np.full_like(s,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [47]:
# random decimal numbers
np.random.rand(2,3)

array([[0.51814211, 0.34245153, 0.58088617],
       [0.40325563, 0.93131804, 0.35990844]])

In [48]:
# random integer values
np.random.randint(7,size=(3,3))
''' In this example, each element of the 3x3 array is a random integer between 0 (inclusive) and 7 (exclusive).
The actual values will vary each time you run the code due to the randomness involved.'''

' In this example, each element of the 3x3 array is a random integer between 0 (inclusive) and 7 (exclusive).\nThe actual values will vary each time you run the code due to the randomness involved.'

In [49]:
np.random.randint(2,7,size=(3,3))

array([[4, 4, 6],
       [6, 3, 3],
       [4, 5, 2]])

In [50]:
np.random.randint(-4,12,size=(3,3))

array([[ 6, -4,  1],
       [ 6,  2,  8],
       [ 2, -2, 10]])

In [51]:
# the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
# repeat array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [53]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [54]:
op = np.ones((5,5))
print(op)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [55]:
op = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

op[1:4,1:4] = z
print(op)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
''' op[1:4, 1:4] = z: This line of code is using slicing to assign the values of the z array to a
specific subarray within the op array. Let's break it down:

op[1:4, 1:4]: This selects a subarray of op that starts from row 1 and ends at row 4 (exclusive), 
and starts from column 1 and ends at column 4 (exclusive). This subarray is a 3x3 region within the larger op array.

= z: This assigns the values of the z array to the selected subarray of op.
As a result, the central 3x3 region of op is replaced with the values of the z array,
and the element at row 1, column 1 of op becomes 9.

print(op): This prints the modified op array.'''

" op[1:4, 1:4] = z: This line of code is using slicing to assign the values of the z array to a\nspecific subarray within the op array. Let's break it down:\n\nop[1:4, 1:4]: This selects a subarray of op that starts from row 1 and ends at row 4 (exclusive), \nand starts from column 1 and ends at column 4 (exclusive). This subarray is a 3x3 region within the larger op array.\n\n= z: This assigns the values of the z array to the selected subarray of op.\nAs a result, the central 3x3 region of op is replaced with the values of the z array,\nand the element at row 1, column 1 of op becomes 9.\n\nprint(op): This prints the modified op array."

In [57]:
op = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

op[1:4,1:4] = 0
print(op)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
op = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

op[1:-1,1:-1] = 7
print(op)

[[1. 1. 1. 1. 1.]
 [1. 7. 7. 7. 1.]
 [1. 7. 7. 7. 1.]
 [1. 7. 7. 7. 1.]
 [1. 1. 1. 1. 1.]]


In [59]:
# be careful when copying arrays!!!
i = np.array([1,2,3])
i = w
print(w)

NameError: name 'w' is not defined

In [60]:
i = np.array([1,2,3])
w = i
print(w)
w[0] = 66
print(w)
print(i)

[1 2 3]
[66  2  3]
[66  2  3]


In [61]:
i = np.array([1,2,3])
w = i.copy()
w[0] = 66
print(i)
print(w)

[1 2 3]
[66  2  3]


In [62]:
# mathematics
v  = np.array([6,2,9,5])
print('actual value = ' , v)
print('add 3 = ' ,v+3)
print('sub 2 = ' ,v-2)


actual value =  [6 2 9 5]
add 3 =  [ 9  5 12  8]
sub 2 =  [4 0 7 3]


In [63]:
v*3

array([18,  6, 27, 15])

In [64]:
v/2

array([3. , 1. , 4.5, 2.5])

In [65]:
v**4

array([1296,   16, 6561,  625], dtype=int32)

In [66]:
v +=10
print(v)

[16 12 19 15]


In [67]:
e = np.array([8,5,9,3])
r = np.array([2,5,4,1])
e+r

array([10, 10, 13,  4])

In [68]:
v  = np.array([6,2,9,5])
np.cos(v)

array([ 0.96017029, -0.41614684, -0.91113026,  0.28366219])

In [69]:
# https://github.com/KeithGalli/NumPy/blob/master/NumPy%20Tutorial.ipynb

#### linear algebra


In [70]:
u = np.full((2,3),1)
print(u)
y = np.full((3,2),2)
print(y)
u*y

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [71]:
u = np.full((2,3),1)
print(u)
y = np.full((3,2),2)
print(y)
print("'solved -'")
print(np.matmul(u,y))

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
'solved -'
[[6 6]
 [6 6]]


In [72]:
u = np.full((2,5),1)
print(u)
y = np.full((3,2),2)
print(y)
print("'solved -'")
print(np.matmul(u,y))

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
'solved -'


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [73]:
# find the determinant 
c = np.identity(3)
np.linalg.det(c)   #determinant 


1.0

In [74]:
# indexing :
# https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html

# determinant
# trace
# singular vector decomposition
# eigenvalues
# matrix norm
# inverse
# etc...

In [75]:
# Array Creation Routines:
# https://numpy.org/doc/stable/reference/routines.array-creation.html

In [76]:
# Math Routines Docs:
# https://numpy.org/doc/stable/reference/routines.math.html

In [77]:
# Linear Algebra Docs: 
# https://numpy.org/doc/stable/reference/routines.linalg.html

#### Statistics

In [78]:
d = np.array([[1,2,3],[4,5,6]])
print(np.max(d))
print(np.min(d))

6
1


In [79]:
# axis = 0 which checks column wise
# axis = 1 which check row wise

In [80]:
d = np.array([[1,2,3],[4,5,6]])
print(np.min(d,axis=1))

[1 4]


In [81]:
d = np.array([[1,2,3],[4,5,6]])
print(np.min(d,axis=0))

[1 2 3]


In [82]:
d = np.array([[1,2,3],[4,5,6],[3,6,9]])
print(np.min(d,axis=1))

[1 4 3]


In [83]:
d = np.array([[1,2,3],[4,5,6],[3,6,9]])
print(np.min(d,axis=0))

[1 2 3]


In [84]:
d = np.array([[1,2,3],[4,5,6],[3,6,9]])
print(np.min(d,axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

In [85]:
np.sum(d)

39

In [86]:
np.sum(d,axis = 0)

array([ 8, 13, 18])

In [87]:
np.sum(d,axis = 1)

array([ 6, 15, 18])

#### Reorganizing Arrays


In [88]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [89]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [90]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [91]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [92]:
after = before.reshape((2,6))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,6)

In [93]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

In [7]:
# load data from file
# Specify the file path
file_path = 'data.txt'  # Replace 'data.txt' with the actual file name or path "C:\Users\sweth\Desktop\data.txt"

# Load data from the file
data = np.genfromtxt(file_path, delimiter=',')

# Display the loaded data
print(data)



FileNotFoundError: data.txt not found.

In [9]:
# you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

np.any(filedata>50,axis=0) 

'''it checks the column one by one if the elements in the 
column greater than 50 it returns true or else false'''

((filedata > 50) & (filedata < 100))

''' its returns true if the element is between 50 and 100 , 
else false '''

(~((filedata > 50) & (filedata < 100)))
' reverse of the above code '

In [ ]:
'''
1  2  3  4  5 
6  7  8  9  10
11 12 13 14 15
16 17 18 19 20
21 22 23 24 25
26 27 28 29 30     #here you should get 11 12
                                        16 17
'''

' solu = a[2:4,0:2] '

''' 2
      8
        14
           20 '''  # we need to print those elements from the matrix

' solu = a[[0,1,2,3] , [1,2,3,4]] '

''' 4  5

    24 25
    29 30 ''' #print this

'  solve = a[[0,4,5] , 3: ]'



#### indexing


In [12]:
x = np.arange(10)
print(x)
print(x[2])
print(x[-2])



[0 1 2 3 4 5 6 7 8 9]
2
8
